version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: export KEYSTORE path
          command: echo 'export KEYSTORE=$(pwd)/signing.jks' >> $BASH_ENV
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
            name: chmod permissions
            command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build assembleRelease
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
    deploy:
        steps:
          - run:
              name: Deploy to Play Store
              command: |
                ./scripts/ci_deploy.sh ${https://we.tl/lB8Lds5hNi} ${https://we.tl/lB8Lds5hNi} ${CIrcleCI} ${https://circleci.com/gh/psk56/CIrcleCI/tree/master}
          - store_artifacts:
              path: /opt/workspace/app/build/outputs/apk/
              destination: apks/
          - store_artifacts:
              path: /opt/workspace/app/build/outputs/mapping/
              destination: mapping/
