version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: export KEYSTORE path
          command: echo 'export KEYSTORE=$(pwd)/signing.jks' >> $BASH_ENV
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
            name: chmod permissions
            command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build assembleRelease
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
    deploy:
      name: Deploy to Play Store
      command: |if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "AnySoftKeyboard" ]; then
                  ./scripts/ci_deploy.sh $KEYSTORE_FILE_URL $PUBLISH_CERT_FILE_URL
                fi

        - store_artifacts:
              path: app/build/outputs/apk/
              destination: apks/

        - store_artifacts:
              path: app/build/outputs/mapping/
              destination: mapping/

        - save_cache:
                  key: anysoftkeyboard-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                  paths:
                    - "~/.gradle/3.4.1"
                    - "~/.gradle/wrapper/dists/gradle-3.4.1-bin"
                    - "~/.gradle/caches/modules-2"
                    - "~/.gradle/buildOutputCleanup"
                    - "~/.m2"
